# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Setting1_Ft
model_type: IR3InputModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: All-Train
    type: AllInOneCLIPDataset
    dataroot_gt: ['/path/to/snow/gt','/path/to/rain/gt,'/path/to/raindrop/gt'] #need to modify
    dataroot_lq:  ['/path/to/snow/lq','/path/to/rain/lq,'/path/to/raindrop/lq'] #need to modify

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256 
    use_flip: true 
    use_rot: true 

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Raindrop-test 
    type: PairedImageCLIPDataset
    dataroot_gt: /path/to/raindrop/test/gt #need to modify
    dataroot_lq: /path/to/raindrop/test/lq #need to modify
    io_backend:
      type: disk


network_g:
  type: PriorFtModelL
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  train_size: [1,3,256,256]
  r: 8
  num_experts: 3
  top_k: 1

network_clip:
  cls_num: 3
  vision_tower: openai/clip-vit-large-patch14-336
  ckpt: /path/to/setting1_router.pth #need to modify

# path
path:
  pretrain_network_g: /path/to/stage1/model.pth #need to modify
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000
    eta_min: !!float 1e-5

  total_iter: 100000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3 
  save_img: false  


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true 
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true 

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500